### ISSUE TITLE
Twig Extension ?

### ISSUE THREAD

**Issue by jayesbe** [snc/SncRedisBundle#224]
So I was wondering.. what the best way to retrieve information from a redis store would be if all I wanted was some text or a count.  So I created a twig extension.

```<?php
namespace AppBundle\Twig\Extension;

use Predis\ClientInterface;

class RedisExtension extends \Twig_Extension
{
    private $predis;

    public function __construct(ClientInterface $predis)
    {
        $this->predis = $predis;
    }

    /**
     *
     * {@inheritdoc}
     *
     */
    public function getFilters()
    {
        return array(
                'redis' => new \Twig_Filter_Method($this, 'predis')
        );
    }

    /**
     * Fetch data at $key in Redis
     *
     * @param string $key
     * @param string $default
     *
     * @return mixed
     */
    public function predis($key, $command, $default = "")
    {
        $res = strval($this->predis->{$command}($key));
        if (empty($res)) {
            return $default;
        }
        return $res;
    }

    /**
     * Returns the name of the extension.
     *
     * @return string The extension name
     */
    public function getName()
    {
        return 'predis_extension';
    }
}
```

Just wondering if this is either good or bad.  Any thoughts ?

**Comment by jayesbe** [comment]
Oh. Im using it as such
```
{{ ('user:'~app.user.id~':'~'totals:matches')|redis('scard') }}
```

or 

```
{{ 'some:redis:key'|redis('get') }}
```

**Comment by Ma27** [comment]
:-1: IMHO redis should be part of the business logic and not be mixed with the view

**Comment by snc** [comment]
Thanks for sharing your code. I agree with Ma27.

**Comment by jayesbe** [comment]
It would be nice to have a bit of a better discussion with more individuals. I disagree with the others for two reasons. The simplicity of it is unparalleled. It uses redis as a view layer cache. 

It also uses the twig extension in a way it was designed in that it transforms a "key" to a "value". Similar to say the translation extension. 

Of course I will continue to use it like this lol.. because its just too easy and works beautifully. But it would be nice to have a wider discussion is all im saying. 

Cheers

**Comment by Ma27** [comment]
well being honestly I absolutly disagree with the concept of such
extensions. There are proper use cases for extensions, but the must not be
"abused" for mixing business logic and view stuff.
The reason by templating engines like mustache or twig exist is that it was
necessary to separate business logic from the view. Twig does IMHO too much
in the view (such as regexes or other weird magic).
Well, Redis can be used as a cache, but actually it is a memory-based
database. If we start supporting databases in twig, what will come next? A
doctrine-twig-extension for DQL?
Such tasks must be done in the controller as it has been made for that.

2015-12-20 11:32 GMT+01:00 Jayes <notifications@github.com>:

**Comment by jayesbe** [comment]
Again to play devils advocate. You do realize that's exactly how LAZY loading Doctrine objects works ?

If you have some object say User that has a relation to some object say Profile where Profile is a LAZY loaded relation.  In Twig performing something like {{ app.user.profile.description }} would (if the object has not already been loaded) make execute a query to the db to fetch back the required data.

I don't agree with redis being strictly Business logic.  When its really Data logic. 

Doing a Redis Get has no business function whatsoever. Obviously as part of some business requirement, data may be requried from a Redis store. That doesn't mean Redis is meant strictly for Business logic.

**Comment by Ma27** [comment]
well, the reason behind doctrine is to provide a mapper which is able to map data from any database (there exist a few NoSQL implementations, too) on your business model including relations to other models.
WHen having some really complex relations, eager loading is a really bad decision, so lazy initialization of associations is pretty good.

But there's one big difference: having twig extensions for SQL (e.g. from Doctrine DBAL) or your redis extension are business logic (well, data logic is IMHO even worse to keep it in templates). The ORM is simply an implementation detail.
While you put business/data logic in your template creating a redis extension, you simply put a model in your template when using doctrine ORM.
What happens when initializing associations is just an implementation __detail__.
Therefore you just have a model in your template and no such data logic. If you would do all your redis stuff in an abstracted way, it would be IMHO fine
