### ISSUE TITLE
Disable caching for config_dev.yml

### ISSUE THREAD

**Issue by bourdeau** [snc/SncRedisBundle#285]
Hi there,

I looked in the doc, on the web, in the issues but I didn't find an easy way to disable Redis when being in dev env (except messing around with how the kernel load bundles, but it's no a valid option according to me). I know this issue has already been mentioned in #253

It would be really nice as for now one might have some surprises developing with redis on.

Thanks for your attention

**Comment by talisman-innovations** [comment]
Hi

I managed to setup Symfony so that I have no redis in the dev environment, but have it configured for test and prod environments.  

Add the bundle to composer
Add the snc_redis: configuration to config_test.yml and config_prod.yml.
Add the following to AppKernel.php 

      if (in_array($this->getEnvironment(), array('prod', 'test'), true)) {
            $bundles[] = new Snc\RedisBundle\SncRedisBundle();
        }

Seems to work fine for me.  You can adjust if you don't want redis in the test environment etc.

Steve

**Comment by robbeman** [comment]
This solution works fine, but if you want to inject the service somewhere (or get it from the container) you'll get ServiceNotFoundExceptions.

It would be nice if there was something like a "dev client" which has all the methods the regular redis client has, but just doesn't cache. Or something. (I'll try to cook something up and post it back here.)

**Comment by robbeman** [comment]
I kind of hacked it:
I made this class:
```
class DummyRedis extends \Redis
{
  public function __construct( ) {}

  // override any method you are using to prevent actual redis caching
}
```
And added this to "services_dev.yml"
```
services:
  snc_redis.default:
    class: APIBundle\Services\DummyRedis
```

All other redis config was moved to "_prod.yml" files and appkernel only activates when in production. Not a perfect solution, but it works.

**Comment by curry684** [comment]
This is considered bad practice in recommended 12 factor app workflows: https://12factor.net/dev-prod-parity

Using tools like Docker or VMs it should easily be possible to keep dev/prod parity including tools like Redis as is highly recommended.

If just using Redis as a caching solution consider using `symfony/cache` instead of this bundle, as the cache-specific implementation does allow TTL-0 caching.
