### ISSUE TITLE
[Question]  differences between SncRedisBundle , Symfony Redis Cache adapter, and Doctring Redis Cache adapter?

### ISSUE THREAD

**Issue by hal869** [snc/SncRedisBundle#394]
_*This*_ bundle's current code "Provides compatibility with Symfony 4"
and is referenced in numerous implementations of Doctrine 2nd level caching

> Three Symfony2 database optimisation tips to implement today
https://www.ekreative.com/three-symfony2-database-optimisation-tips-to-implement-today/

> Doctrine’s Second Level Cache in a Symfony Application
https://www.pgs-soft.com/doctrines-second-level-cache-in-a-symfony-application/

> Doctrine Second Level Cache with Translations and Redis
https://kunicmarko20.github.io/2017/07/20/Doctrine-Second-Level-Cache-with-Translations-and-Redis.html

> Doctrine Second Level Cache w/ Redis
https://stackoverflow.com/questions/32289787/doctrine-second-level-cache-w-redis

Doctrine directly provides a Redis Cache Adaptor, (http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/caching.html#redis, https://symfony.com/doc/master/bundles/DoctrineCacheBundle/reference.html#predis)

Symfony4 does as well (https://symfony.com/doc/current/components/cache/adapters/redis_adapter.html)

What specific functionality/usage does SncRedisBundle provide that the Doctrine & Symfony4 adapters do not? 
Generally, as well as specifically with regard to 2nd level caching in doctrine?

**Comment by curry684** [comment]
Redis is, despite often being seen as such, not a caching tool. Redis is a highly performant in memory data processing engine, capable of even pubsub messaging, geopositioning queries and much much more. This bundle deeply integrates Redis into your Symfony application as configured, and exposes all native Redis functionality natively. 

The adapters you mention just use Redis as a caching solution.

As for 2nd level caching - it's [still marked experimental by Doctrine team itself](http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/second-level-cache.html). I've never seen it work reliably in any experiment I've ever tried, and am not really inclined to "fix" this bundle's compatibility as long as the functionality is not even "beta" or otherwise close to becoming a production recommendation.

**Comment by curry684** [comment]
Considering this answered.
