### ISSUE TITLE
Symfony 4 autowire

### ISSUE THREAD

**Issue by Webonaute** [snc/SncRedisBundle#426]
hi.

how can I autowire redis service to my other commands/services? is that even possible?

I think it will need some kind of ClientInterface so using predis or phpredis configurations not become a problem.

**Comment by Webonaute** [comment]
seem that its possible by creating an interface for Client class.

than in DI, you add code like this 👍 
`$container->getDefinition('monolog.logger')->addAutowiringType('Psr\Log\LoggerInterface');`

**Comment by Majkl578** [comment]
See https://github.com/snc/SncRedisBundle/issues/367.

**Comment by buffcode** [comment]
+1 for adding a common interface to both `Client` classes. The dependency injection should then (if not already the case) only add the configured service to the container. This way the auto wiring should work and pick up the correct service as configured by the user, whichever that may be.

**Comment by curry684** [comment]
Problem is that it would put the burden on us to maintain a generic bridge interface with in total over a hundred methods... there is a good reason it wasn't done like that in the first place, and it's become worse now that phpRedis has switched to strict typing.

**Comment by curry684** [comment]
I noticed a few days ago (thanks to phpstan) that this is nigh on impossible, as phpredis 4.0 is just plain wrong with its type hints in multiple locations for both parameters and return values. Like I said before, the mess of incompatibility between Predis and phpredis is not a burden that I think this bundle should carry.

I'm closing this issue since the original question is answered, you can just alias `Redis` to `snc_redis.default` or another connection, ie:
```
services:
    Redis: '@snc_redis.default'
```
With this in place, any reference to `\Redis` will autowire correctly in Symfony 3.4+.
