### ISSUE TITLE
AWS Redis 5 master-replica

### ISSUE THREAD

**Issue by jaumebosch** [snc/SncRedisBundle#504]
Hi, 
is there any way to configure the redis client to use the AWS Elasticache Redis5  with a master-replica configuration?

Thanks

**Comment by B-Galati** [comment]
Hi,

I have no idea sorry. Please submit a PR to the doc if you find something ;-)

**Comment by curry684** [comment]
I don't think this is a scenario any of us have been using, but I suspect it's not up to the bundle to implement as really we're a pretty thin wrapper around either Predis or phpRedis. So indeed, if you manage to get it to work by all means document it   😆 

I'll close the issue for now as there's really nothing to do at this point rather than experimentation by someone with access to such a setup. If you run into specific problems we'd better tackle those in specific issues.
