### ISSUE TITLE
Supporting Relay

### ISSUE THREAD

**Issue by tillkruss** [snc/SncRedisBundle#679]
Hey 👋

I'm the maintainer of Predis and teamed up with the maintainer of PhpRedis, @michael-grunder to build a new Redis extension for PHP called [Relay](https://github.com/cachewerk/relay) and we'd love to integrate with Symfony.

We're a bit clueless when it comes to Symfony and it's ecosystem and are looking for advice.

Symfony seems to have it's own Redis components, what's the difference to this repo?
Should we add support for Relay via this repo, or fork it?

**Comment by ostrolucky** [comment]
What this bundle does is basically:
- provides a profiling/debugging panel, as well provides data for other panels
- integrates logging for the queries being made
- provides client independent configuration of redis client with validation, instead of getting errors during runtime

And yeah, Relay would be a welcome addition. Check PhpredisClientFactory for inspiration, you should be able to figure out what should be adapted for Relay. Rest of the work is not much.

That said, I think what this bundle needs more than Relay support at the moment is Predis 2.x support.
