### ISSUE TITLE
Dependency on deprecated symfony/proxy-manager-bridge

### ISSUE THREAD

**Issue by astronom** [snc/SncRedisBundle#713]
Since [symfony/proxy-manager-bridge:^6.3](https://github.com/symfony/proxy-manager-bridge/blob/6.3/CHANGELOG.md#63) package marked as deprecated. The proxy functionality was implemented in [symfony/var-exporter](https://symfony.com/blog/revisiting-lazy-loading-proxies-in-php)

In order not to break BC it is possible to update this line with condition

https://github.com/snc/SncRedisBundle/blob/master/src/DependencyInjection/SncRedisExtension.php#L236

```php
use Symfony\Component\VarExporter\ProxyHelper;
...
 $phpredisDef->setLazy(class_exists(ProxyDumper::class) || class_exists(ProxyHelper::class));
```

But I'm not sure what to do with the composer requierments

**Comment by ostrolucky** [comment]
Perhaps we could just set it to `true`. I'm not sure why class_exists has been added there https://github.com/snc/SncRedisBundle/pull/672.

Any thoughts @nicolas-grekas?

As for composer requirements, there are none. These packages are not required, that's why class_exists check. But we should remove the bridge from suggests section.
